/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.teste.telas;

import br.com.teste.dal.ModuloConexao;
import java.text.DateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import java.sql.*;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Usuário
 */
public class TelaPrincipal extends javax.swing.JFrame {

    Connection conexao = null;
    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        conexao = ModuloConexao.conector();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dp_Principal = new javax.swing.JDesktopPane();
        lb_LogoSV = new javax.swing.JLabel();
        lb_Usuario = new javax.swing.JLabel();
        lb_Data = new javax.swing.JLabel();
        menu_Principal = new javax.swing.JMenuBar();
        mn_Cad = new javax.swing.JMenu();
        mn_Cad_Cli = new javax.swing.JMenuItem();
        mn_Cad_Os = new javax.swing.JMenuItem();
        mn_Cad_Us = new javax.swing.JMenuItem();
        mn_Rel = new javax.swing.JMenu();
        mn_Rel_Clientes = new javax.swing.JMenuItem();
        mn_Rel_Ser = new javax.swing.JMenuItem();
        mn_Aj = new javax.swing.JMenu();
        mn_Aj_So = new javax.swing.JMenuItem();
        mn_Op = new javax.swing.JMenu();
        mn_Op_Sa = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Controle para OS");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        dp_Principal.setPreferredSize(new java.awt.Dimension(520, 480));

        javax.swing.GroupLayout dp_PrincipalLayout = new javax.swing.GroupLayout(dp_Principal);
        dp_Principal.setLayout(dp_PrincipalLayout);
        dp_PrincipalLayout.setHorizontalGroup(
            dp_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
        );
        dp_PrincipalLayout.setVerticalGroup(
            dp_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        lb_LogoSV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/teste/icones/SV 01.png"))); // NOI18N

        lb_Usuario.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lb_Usuario.setText("Usuário");

        lb_Data.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lb_Data.setText("Data");

        mn_Cad.setText("Cadastro");

        mn_Cad_Cli.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_DOWN_MASK));
        mn_Cad_Cli.setText("Cliente");
        mn_Cad_Cli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_Cad_CliActionPerformed(evt);
            }
        });
        mn_Cad.add(mn_Cad_Cli);

        mn_Cad_Os.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.ALT_DOWN_MASK));
        mn_Cad_Os.setText("OS");
        mn_Cad_Os.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_Cad_OsActionPerformed(evt);
            }
        });
        mn_Cad.add(mn_Cad_Os);

        mn_Cad_Us.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.ALT_DOWN_MASK));
        mn_Cad_Us.setText("Usuário");
        mn_Cad_Us.setEnabled(false);
        mn_Cad_Us.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_Cad_UsActionPerformed(evt);
            }
        });
        mn_Cad.add(mn_Cad_Us);

        menu_Principal.add(mn_Cad);

        mn_Rel.setText("Relatório");
        mn_Rel.setEnabled(false);

        mn_Rel_Clientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.ALT_DOWN_MASK));
        mn_Rel_Clientes.setText("Clientes");
        mn_Rel_Clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_Rel_ClientesActionPerformed(evt);
            }
        });
        mn_Rel.add(mn_Rel_Clientes);

        mn_Rel_Ser.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_DOWN_MASK));
        mn_Rel_Ser.setText("Serviços");
        mn_Rel_Ser.setToolTipText("");
        mn_Rel.add(mn_Rel_Ser);

        menu_Principal.add(mn_Rel);

        mn_Aj.setText("Ajuda");

        mn_Aj_So.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, java.awt.event.InputEvent.ALT_DOWN_MASK));
        mn_Aj_So.setText("Sobre ");
        mn_Aj_So.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_Aj_SoActionPerformed(evt);
            }
        });
        mn_Aj.add(mn_Aj_So);

        menu_Principal.add(mn_Aj);

        mn_Op.setText("Opções");

        mn_Op_Sa.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_DOWN_MASK));
        mn_Op_Sa.setText("Sair");
        mn_Op_Sa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_Op_SaActionPerformed(evt);
            }
        });
        mn_Op.add(mn_Op_Sa);

        menu_Principal.add(mn_Op);

        setJMenuBar(menu_Principal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(dp_Principal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_Data, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lb_Usuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(lb_LogoSV)
                        .addContainerGap(75, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(dp_Principal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(lb_Usuario)
                        .addGap(65, 65, 65)
                        .addComponent(lb_Data)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lb_LogoSV)))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        Date data = new Date();
        DateFormat formatador = DateFormat.getDateInstance(DateFormat.SHORT);
        lb_Data.setText(formatador.format(data));
    }//GEN-LAST:event_formWindowActivated

    private void mn_Aj_SoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_Aj_SoActionPerformed
        TelaSobre sobre  = new TelaSobre();
        sobre.setVisible(true);
    }//GEN-LAST:event_mn_Aj_SoActionPerformed

    private void mn_Op_SaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_Op_SaActionPerformed
        int sair = JOptionPane.showConfirmDialog(null,"Tem certeza que deseja sair?","Atenção",JOptionPane.YES_NO_OPTION);
        if(sair == JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_mn_Op_SaActionPerformed

    private void mn_Cad_UsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_Cad_UsActionPerformed
        TelaUsuario usuario = new TelaUsuario();
        usuario.setVisible(true);
        dp_Principal.add(usuario);
    }//GEN-LAST:event_mn_Cad_UsActionPerformed

    private void mn_Cad_CliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_Cad_CliActionPerformed
        TelaCliente cliente = new TelaCliente();
        cliente.setVisible(true);
        dp_Principal.add(cliente);
    }//GEN-LAST:event_mn_Cad_CliActionPerformed

    private void mn_Cad_OsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_Cad_OsActionPerformed
        TelaOs tOs = new TelaOs();
        tOs.setVisible(true);
        dp_Principal.add(tOs);
    }//GEN-LAST:event_mn_Cad_OsActionPerformed

    private void mn_Rel_ClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_Rel_ClientesActionPerformed
        int confirma = JOptionPane.showConfirmDialog(null, "Confirma a impressão do relatório?","Atenção",JOptionPane.YES_NO_OPTION);
        if(confirma == JOptionPane.YES_OPTION){
            try {
                JasperPrint print = JasperFillManager.fillReport("C:/Users/Usuário/Documents/AplicativoTeste/Reports/Clientes.jasper",null,conexao);
                JasperViewer.viewReport(print, false);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null,e);
                System.out.println(e);
            }
        }
    }//GEN-LAST:event_mn_Rel_ClientesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dp_Principal;
    private javax.swing.JLabel lb_Data;
    private javax.swing.JLabel lb_LogoSV;
    public static javax.swing.JLabel lb_Usuario;
    private javax.swing.JMenuBar menu_Principal;
    private javax.swing.JMenu mn_Aj;
    private javax.swing.JMenuItem mn_Aj_So;
    private javax.swing.JMenu mn_Cad;
    private javax.swing.JMenuItem mn_Cad_Cli;
    private javax.swing.JMenuItem mn_Cad_Os;
    public static javax.swing.JMenuItem mn_Cad_Us;
    private javax.swing.JMenu mn_Op;
    private javax.swing.JMenuItem mn_Op_Sa;
    public static javax.swing.JMenu mn_Rel;
    private javax.swing.JMenuItem mn_Rel_Clientes;
    private javax.swing.JMenuItem mn_Rel_Ser;
    // End of variables declaration//GEN-END:variables
}
